### ISSUE TITLE
accounts: adding "skype" shows error (some other telepathy-haze requiring services aswell)

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#11]
![screenshot_20180224_135139](https://user-images.githubusercontent.com/840070/36630626-ed50df3e-1969-11e8-93d5-799864b15300.png)

**Comment by llelectronics** [comment]
Same problem for icq or yahoo messenger which also need **telepathy-haze**. 
The package itself is installed.

**Comment by llelectronics** [comment]
Like discussed removed all of the haze and most of the other accounts with these commits: 
https://github.com/netrunner-core/netrunner-core/commit/293dd97ec427745a673dea4daadc85a15addb101
https://github.com/netrunner-core/netrunner-core/commit/40bda5b15d5ed2cfd90b4ae67acb58435c69f072
https://github.com/netrunner-core/netrunner-core/commit/4c7321e1cc2780d046c8ff603a51b9b009d1791f
