### ISSUE TITLE
apt update fails (due to repo not found?)

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#12]
![screenshot_20180224_140700](https://user-images.githubusercontent.com/840070/36630767-118ace76-196c-11e8-89d2-91652830418c.png)

**Comment by llelectronics** [comment]
Thats the issue we also had in the past when building something against debian snapshot server. 
The reason we want to clone debian snapshot.

**Comment by star-buck** [comment]
The date of the snapshot in URL is in the future?
Does the repo exist?

**Comment by shadeslayer** [comment]
I think it's more of a ipv6/ipv4 issue

**Comment by llelectronics** [comment]
Yes it should exists. Its in the future as it will keep rolling until this date and stays on whatever software is in testing that date.
