### ISSUE TITLE
all versions: add "appmenu-gtk-module"

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#14]

**Comment by llelectronics** [comment]
Both versions? 
E.g. appmenu-gtk2-module && appmenu-gtk3-module  ?

**Comment by star-buck** [comment]
i assume so, if in doubt ask kbroulik (it is for global menu to work properly)

**Comment by llelectronics** [comment]
Yeah I just added both as we want gtk3 and gtk2 apps have the ability. 
See: https://github.com/netrunner-desktop/netrunner-desktop/commit/a1de6c506b86cdaa008af9b0730b9d3daf549f73
