### ISSUE TITLE
only netrunner-desktop: add thunderbird

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#17]

**Comment by star-buck** [comment]
install pulls in mandatory "lightning"?
maybe those should be decoupled, like lightning may be installed, but not needed.

**Comment by llelectronics** [comment]
Lightning is part of thunderbird since a few versions already

**Comment by star-buck** [comment]
Oh okay then. Still is it going to be uninstallable if people dont like it?

**Comment by llelectronics** [comment]
I think it can only be deactivated

**Comment by llelectronics** [comment]
Thunderbird-Plasma is already in the metapackage. It must be some other reason it isn't installing in the live build process.

**Comment by star-buck** [comment]
it is in desktop now?
