### ISSUE TITLE
netrunner-desktop: install yarock

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#19]
yarock should share the same settings as in rolling version, look here:
https://github.com/netrunner-rolling/2018.01/issues/13

@NuLogicSystems : where is the config file for yarock in github?

**Comment by NuLogicSystems** [comment]
It's installed via packaging:
https://github.com/netrunner-rolling/PKGBUILD-ds9-common/tree/master/default-settings-applications

**Comment by shadeslayer** [comment]
@NuLogicSystems any reasons this isn't in the main git repo but in the PKGBUILD?

**Comment by star-buck** [comment]
yeah, lets make sure shared configs are using the best repo so all benefit from any changes easily.
@shadeslayer : where do you suggest to copy it, so then James can change this for future rolling versions?

**Comment by shadeslayer** [comment]
default-settings-applications seems like the right place

**Comment by star-buck** [comment]
Okay, please go ahead and copy it, then James can figure out how to adjust
pkbuild to match.

**Comment by NuLogicSystems** [comment]
I didn't have access to the original location, I also hate forking stuff. 
It was just quicker and less complicated to install it into the chroot during packaging.

**Comment by star-buck** [comment]
@llelectronics : how to install? i cant seem to find it...

**Comment by llelectronics** [comment]
Packages are built. Did you tried apt update yet before searching for it?

**Comment by star-buck** [comment]
Yes, did not find it though... But it was from live, not installed
version...

**Comment by llelectronics** [comment]
It appears for me after running apt update on yesterdays image. Installs and runs fine aswell.

**Comment by NuLogicSystems** [comment]
I set this to use the mpv backend as per Starbucks request:
https://github.com/netrunner-rolling/2018.01/issues/13#issuecomment-355863005

**Comment by llelectronics** [comment]
Ah ok we did compile it only with phonon and thats why it was complaining. With only one engine being available setting no engine and it picks up the right one apparently.

**Comment by NuLogicSystems** [comment]
Yea, but that means I can't use the upstream config and will still need to install my overlay during packaging.

**Comment by llelectronics** [comment]
No you could just build yarock with only the mpv audio backend instead.

**Comment by NuLogicSystems** [comment]
That is not what Starbuck wanted, he wanted mpv.
Phonon didn't work right and vlc was not an option.

**Comment by llelectronics** [comment]
I don't get your problem then. Just use our config with no audio engine set. compile just the mpv audio backend when you build yarock and voila it will work

**Comment by NuLogicSystems** [comment]
I did what I was asked to do.
I'm not going to compile for only one backend.
I also prefer phonon (gstreamer) myself and change this after install.
I find that kind of reasoning counter productive.

**Comment by llelectronics** [comment]
Added yarock to netrunner-desktop metapackage: https://github.com/netrunner-desktop/netrunner-desktop/commit/62218bb90bdc833787aec7fcf0a93c84aac71fed
