### ISSUE TITLE
all versions: firefox needs ublock blocking rule due to "google hidden throbber under linux"

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#21]
https://github.com/netrunner-rolling/2018.01/issues/40#issuecomment-359765798

add to "ublock - My filters":
```
www.google.*###cnsm` > g-loading-icon
google.*###cnsm > g-loading-icon
```

as soon as this is applied, reload google startpage and see "Web" process go down from 7-10% or more to less than <3%.

**Comment by star-buck** [comment]
missing in CORE

**Comment by NuLogicSystems** [comment]
Firefox Quantum changed the way extensions are handled. The settings for ublock are now kept in a storage.js file likether extensions.
https://github.com/netrunner-rolling/netrunner-settings-firefox/tree/master/etc/skel/.mozilla/firefox/firefox.default/browser-extension-data/uBlock0%40raymondhill.net

**Comment by llelectronics** [comment]
@NuLogicSystems thx for this. 
Added this configuration file for ublock now with this commit: https://github.com/netrunner-common/netrunner-settings-firefox/commit/5793aef3cfbce04842920d5fef545c4041c645f7

**Comment by llelectronics** [comment]
Actually not fixed with todays image as the folder was wrong. 
Now should be fixed in next image with commit: https://github.com/netrunner-common/netrunner-settings-firefox/commit/6df24b960f97b27f9ed8097aa130d9a51ed7b0a9

**Comment by star-buck** [comment]
seems fixed
