### ISSUE TITLE
tb: thunderbird looks weird, needs updates for font-size-changer to be compatible

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#23]
new font sizer changer:
https://addons.mozilla.org/en-US/thunderbird/addon/theme-font-size-changer-for-tb/

after install new one and remove old, the settings should look like this:
![screenshot_20180303_115105](https://user-images.githubusercontent.com/840070/36933466-57e822f2-1ed9-11e8-950e-e2e7196e3849.png)

**Comment by star-buck** [comment]
also the full themes seems both need to be updated, as they are no longer valid.

**Comment by star-buck** [comment]
addon now works with latest TB, but seems is not applied:
if one changes size: costum: to 11.5 and then back to 12 and hits "apply" it looks different:
![screenshot_20180306_211757](https://user-images.githubusercontent.com/840070/37058907-de57315a-2183-11e8-9860-ef52ca651a10.png)
vs.
![screenshot_20180306_211516](https://user-images.githubusercontent.com/840070/37058914-e41da8da-2183-11e8-9d3a-3bd4292fa6e0.png)

**Comment by llelectronics** [comment]
This commit changes this: https://github.com/ds9-common/default-settings-thunderbird/commit/81cd6183bcb5875b9987a982180ac1f3b8c599f9

**Comment by star-buck** [comment]
works
