### ISSUE TITLE
yarock: set audio engine=phonon, volume=50% and systray entry=Always

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#25]
- first open:
![screenshot_20180303_142252](https://user-images.githubusercontent.com/840070/36934769-8ed14b26-1eee-11e8-9348-9a990e54e9b0.png)

- needs to be set to phonon:
![screenshot_20180303_142311](https://user-images.githubusercontent.com/840070/36934776-9c7ddf00-1eee-11e8-823e-30c5b4e04c16.png)

- needs systray entry to be set from "Auto" to "Always"

**Comment by star-buck** [comment]
also needs volume to be set to 50% (default is 0%, so you dont hear anything)

**Comment by llelectronics** [comment]
See: https://github.com/netrunner-core/1803-issues/issues/19#issuecomment-370144895
As we only ship one audio engine not setting any engine makes yarock use the only one available which is phonon.

**Comment by star-buck** [comment]
but here as can be seen in above screenshot it complaints about engine not being set?

**Comment by star-buck** [comment]
when setting an engine like on rolling mpv, this error message doesnt appear

**Comment by llelectronics** [comment]
Have you downloaded and set the config I updated today and linked to? The issue was that we had MPV set as default backend as we just took the config from rolling. As MPV backend isn't even compiled it fails.

**Comment by star-buck** [comment]
SYSTRAY ENTRY is not set to ALWAYS?

**Comment by llelectronics** [comment]
Not done yet.

**Comment by llelectronics** [comment]
Core is not done yet. There was a typo I fixed: https://github.com/netrunner-artwork/artwork-lnf-netrunner-core/commit/03adaaa5d93e7666777b7f369583d86ca1dd2b7e

**Comment by star-buck** [comment]
works on desktop.
