### ISSUE TITLE
libreoffice: adjust style

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#26]
- add libreoffice-gtk2
- writer: switch to "single page view" instead of "multipage view"

**Comment by llelectronics** [comment]
Libreoffice-GTK got renamed apparently to libreoffice-gtk2 (as there is a new gtk3 variant aswell). Changed it here: https://github.com/netrunner-desktop/netrunner-desktop/commit/ff224be590fe2d46de7979e8596dcaf381a9aecf

Setting for LO Writer also set here now: https://github.com/ds9-common/default-settings-applications/commit/722be8c90f30fda9d830a59f9d048d304d9f1e3a

**Comment by star-buck** [comment]
just make sure we use gtk2 for now, as gtk3 filepicker is horrible :)

**Comment by star-buck** [comment]
done
