### ISSUE TITLE
audacious: Song Info: UNTICK Guess missing Metadata from filepath

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#28]
![screenshot_20180303_165403](https://user-images.githubusercontent.com/840070/36936277-8518b348-1f03-11e8-80a1-5d68571914ec.png)

**Comment by llelectronics** [comment]
Changed here: https://github.com/ds9-common/default-settings-applications/commit/47f4470b2fab10176d1237fa854ae273442594ca

**Comment by star-buck** [comment]
works
