### ISSUE TITLE
change default wallpaper for all core and desktop versions

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#3]
https://www.dropbox.com/s/01glax331pkrile/idolon-1920x1080.jpg?dl=0

**Comment by llelectronics** [comment]
Created this git repo here for the desktop wallpaper: https://github.com/netrunner-artwork/artwork-wallpapers-netrunner-1803-desktop

Guess we can use this package for core also as long as the wallpaper stays the same. 
If its planned to have both core and desktop version in the final version aswell we could even rename the git repo and package name and remove the -desktop at the end.

**Comment by star-buck** [comment]
Yes, its for both core and desktop.

**Comment by llelectronics** [comment]
Netrunner Core metapackage should now pull in the **artwork-wallpapers-netrunner-1803-desktop** package: https://github.com/netrunner-core/netrunner-core/commit/dabff3e1de955d373109626bbe2fc5009abfa669
