### ISSUE TITLE
core and desktop: readme icon: point both to: readme-1803

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#33]

**Comment by llelectronics** [comment]
FIxed with: https://github.com/netrunner-desktop/netrunner-desktop-settings-desktop/commit/6ce60bd5a70a4817bee2d22ad0759ee512e1ce4b
& https://github.com/netrunner-core/netrunner-core-settings-desktop/commit/b1ef4a37aa312bf251e74b463511dce12d218a48

**Comment by star-buck** [comment]
works on desktop

**Comment by star-buck** [comment]
and core
