### ISSUE TITLE
LibreOffice not launching / crashing in Live Mode

### ISSUE THREAD

**Issue by llelectronics** [netrunner-core/1803-issues#35]
LibreOffice is crashing with Signal 11 when started in live mode. 
It works fine after installation.

**Comment by star-buck** [comment]
confirmed, now why is that?

**Comment by llelectronics** [comment]
Found the culprit. It is apparmor. Apparently it is denying file access to certain locations and that is unexpected for LO so that it crashes.
On the other side thunderbird does not load lightning other extensions or languages as apparmor denies access aswell.
Quick and easy solution would be adding the boot parameter 
**apparmor=0** to the live bootloader (you can try booting with that option by hitting tab (isolinux) or e (grub) to append that bootoption and everything works again. 
As it only happens in live mode and apparmor rules are working fine after install it might be that the live boot scripts do something unexpected for apparmor. 
Anyways my suggestion is disabling it for the live system altogether as it makes not much sense there.

**Comment by star-buck** [comment]
Good find and agreed to disable in live mode.

**Comment by llelectronics** [comment]
Should be fixed with these commits: https://github.com/netrunner-desktop/live-build/commit/d451ddd40bd58c0af5962512cb7cec69594ea36b
https://github.com/netrunner-core/live-build/commit/d4a156e70dc9530294cc93b4d3b252c3f4c2baaf

**Comment by star-buck** [comment]
works with latest desktop iso
