### ISSUE TITLE
Desktop: TB: add addon: MS Office

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#37]
https://addons.mozilla.org/en-US/thunderbird/addon/ms-office-2003-jb-edition/?src=cb-dl-users

dont make default though

**Comment by llelectronics** [comment]
This commit adds MsOffice Theme disabled by default: https://github.com/ds9-common/default-settings-thunderbird/commit/81cd6183bcb5875b9987a982180ac1f3b8c599f9

**Comment by shadeslayer** [comment]
Seems to work now
