### ISSUE TITLE
all versions: remove isowriter from menu, install imagewriter

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#4]

**Comment by llelectronics** [comment]
Removed the modified desktop file from here: https://github.com/ds9-common/default-settings-applications/commit/ec7046aa371b86873323c57d9ef3085760d81cfe

**Comment by llelectronics** [comment]
Also added imagewriter to recommends: https://github.com/netrunner-core/netrunner-core/commit/c070ddaf787d861729b72fe2c761f17149795d85

**Comment by star-buck** [comment]
@shadeslayer : not working on latest desktop iso

**Comment by llelectronics** [comment]
Done now for desktop aswell: https://github.com/netrunner-desktop/netrunner-desktop/commit/5758f23a96ba72f1d64872c9f2f098014a7efa98
