### ISSUE TITLE
desktop: obvious: Firefox ESR is installed again

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#40]
![screenshot_20180309_133431](https://user-images.githubusercontent.com/840070/37207743-9bd2ba4e-239e-11e8-8eaf-844de53b99c6.png)

**Comment by llelectronics** [comment]
Fixed with: https://github.com/netrunner-desktop/calamares-desktop/commit/31adcd573e17d5701daa7c6b8d2c38fca3661761
