### ISSUE TITLE
desktop: FF: not German even though installed as german langauge

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#41]
everything else seems German so far, even TB.

**Comment by llelectronics** [comment]
Yeah we forgot to change the language packs installed from firefox-esr to firefox. That causes also the firefox-esr package to be installed with the installation. 
Fixed here: https://github.com/netrunner-desktop/calamares-desktop/commit/31adcd573e17d5701daa7c6b8d2c38fca3661761
