### ISSUE TITLE
FF: toolbar: additional GAP on right side between downloads icon and new window, remove "show sidebars" icon again

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#42]
![screenshot_20180309_141041](https://user-images.githubusercontent.com/840070/37208977-ba507b82-23a3-11e8-8ec7-6c99f4082c7e.png)

![screenshot_20180309_141027](https://user-images.githubusercontent.com/840070/37208987-be8fa56a-23a3-11e8-96e0-10abebcd98bf.png)

**Comment by star-buck** [comment]
also: remove last icon "show sidebars" again

**Comment by star-buck** [comment]
also switch new window and download icon, end result of all changes should look like this:
![screenshot_20180309_141511](https://user-images.githubusercontent.com/840070/37209140-5f2231be-23a4-11e8-9d31-5284982182cb.png)

**Comment by llelectronics** [comment]
It does look like this on my install. The problem only exists if you started firefox-esr in between as it messes with the settings and I can reproduce the issue you post here. 
With firefox-esr gone everything should be ok.

**Comment by star-buck** [comment]
it looks EXACTLY as above? the icons in the absolute same order?

**Comment by llelectronics** [comment]
This is how it looks like: 
![netrunner-desktop-ff](https://user-images.githubusercontent.com/3415572/37211332-d947d550-23ab-11e8-9ffa-69d91f2c312f.png)
