### ISSUE TITLE
fonts for ROOT GTK apps look weird

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#6]
![screenshot_20180223_193802](https://user-images.githubusercontent.com/840070/36610996-527ee330-18d2-11e8-9eba-46e20b5535aa.png)

**Comment by star-buck** [comment]
maybe switch to Deja Sans Book 9px default

**Comment by llelectronics** [comment]
Changed it now here: https://github.com/netrunner-common/netrunner-settings-theming/commit/6a97b0e1eeb932f1f1e37263980d6530b47336d7

Looks slightly better now: 
![dejavu-sans-book9](https://user-images.githubusercontent.com/3415572/36740114-cb29a20e-1be1-11e8-9fde-88f3bad96361.png)
