### ISSUE TITLE
remove all entries in kservices5 and replace with new ones

### ISSUE THREAD

**Issue by star-buck** [netrunner-core/1803-issues#7]
remove all entries first (not simple "overwrite"):
https://github.com/ds9-common/default-systemsettings-settings/tree/master/kservices5

and extract new ones: https://www.dropbox.com/s/5kg193yqhjonndp/kservices5.rar?dl=0

**Comment by llelectronics** [comment]
Applied: https://github.com/ds9-common/default-systemsettings-settings/commit/694551fd20fc63c7eeacd0bc5747b6de98458a1c

**Comment by star-buck** [comment]
Did you DELETE ALL ENTRIES and put all new ones there?

**Comment by star-buck** [comment]
looks identical though, lets wait for new ISO to see if all applied correctly.

**Comment by llelectronics** [comment]
> Did you DELETE ALL ENTRIES and put all new ones there?
Yes thats what I did. Remove the kservice5 folder and put the one from your RAR in
